# -*- coding: utf-8 -*-
"""working on titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwwKUSlijqYGchtZXhomdaqAfzvwIkew
"""

import pandas as pd
# from google.colab import files
# files.upload()
df = pd.read_csv("titanic.csv")
print(df.shape)
print(df.head())

print(df.info())

print(df.isnull().sum())

df.describe()

df['Age'].fillna(df["Age"].mean(),inplace=True)

df.duplicated().sum()

print(df.select_dtypes(include='number').corr()['Survived'])